FROM tomcat:latest

# ADD <src on host> <dest on container>
# ADD jenkins.war /usr/local/tomcat/webapps/
ADD https://get.jenkins.io/war-stable/latest/jenkins.war /usr/local/tomcat/webapps/

EXPOSE 8080