name: C - CI - Livl OS

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make 01-syscalls_fs
      run: cd 01-syscalls_fs && make
    - name: make 02-proc
      run: cd 02-proc && make
    - name: make 04-signals
      run: cd 04-signals && make
